import { SolarCompany } from "@/types/solar";

export const COMPANIES: SolarCompany[] = [
  {
    id: "panasonic",
    name: "パナソニック",
    nameEn: "Panasonic",
    modelName: "EverVolt EVPV430H",
    panelWidthM: 1.053,
    panelHeightM: 1.765,
    panelWatts: 430,
    color: "#0057a8",
    bgColor: "#eff6ff",
  },
  {
    id: "sharp",
    name: "シャープ",
    nameEn: "Sharp",
    modelName: "NU-440CK",
    panelWidthM: 1.053,
    panelHeightM: 1.722,
    panelWatts: 440,
    color: "#d62027",
    bgColor: "#fff1f2",
  },
  {
    id: "choshu",
    name: "長州産業",
    nameEn: "Choshu",
    modelName: "CS-400B72",
    panelWidthM: 1.0,
    panelHeightM: 1.722,
    panelWatts: 400,
    color: "#16a34a",
    bgColor: "#f0fdf4",
  },
  {
    id: "canadian",
    name: "カナディアンソーラー",
    nameEn: "Canadian Solar",
    modelName: "CS6W-550MS",
    panelWidthM: 1.133,
    panelHeightM: 2.172,
    panelWatts: 550,
    color: "#ea580c",
    bgColor: "#fff7ed",
  },
  {
    id: "kyocera",
    name: "京セラ",
    nameEn: "Kyocera",
    modelName: "KJ400P-6NCBG",
    panelWidthM: 1.048,
    panelHeightM: 1.741,
    panelWatts: 400,
    color: "#7c3aed",
    bgColor: "#faf5ff",
  },
  {
    id: "longi",
    name: "LONGiソーラー",
    nameEn: "LONGi Solar",
    modelName: "Hi-MO 6 LR5-72",
    panelWidthM: 1.134,
    panelHeightM: 2.278,
    panelWatts: 580,
    color: "#0891b2",
    bgColor: "#ecfeff",
  },
];
